CREATE TABLE APPLIANCE(
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  STATUS INT,
  DESCRIPTION VARCHAR(2000)
);
insert into APPLIANCE (ID,NAME, STATUS, DESCRIPTION)
VALUES (1,'testName',0,'test description');